dist: trusty
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/cphalcon
    - $HOME/pecl_cache

before_install:
  - pecl channel-update pecl.php.net
  # Install Extensions
  - vendor/bin/ci-install-extensions
  - composer install --prefer-source --no-interaction

script:
  # Check code style
  - vendor/bin/phpcs
  # Running unit test
  - vendor/bin/phpunit --stderr --verbose --coverage-clover=coverage.clover

after_success:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

branches:
  #Don't build tags
  except:
  - /^v\d/
